# Generated by Django 4.2.3 on 2023-07-29 19:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_profile_firstname_alter_profile_lastname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('3fafeb46-3e9f-4f79-8fe0-7495132724de'), primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('no_of_likes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='posts')),
                ('caption', models.TextField()),
            ],
        ),
    ]
