# Generated by Django 4.2.3 on 2023-07-29 19:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(upload_to='post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c18aafcf-1254-4322-a1f9-257c44f5ea67'), primary_key=True, serialize=False),
        ),
    ]
