# Generated by Django 4.2.3 on 2023-07-30 10:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_post_file_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(upload_to='post/body-laguage.png'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('095a5186-cb04-4e27-a8a9-dade1e0c0210'), primary_key=True, serialize=False),
        ),
    ]
