# Generated by Django 4.2.3 on 2023-07-30 10:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_post_file_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(upload_to='post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('eeac4ad2-3d15-487b-a6c6-eae6f0e1ec77'), primary_key=True, serialize=False),
        ),
    ]
