# Generated by Django 4.2.3 on 2023-07-31 14:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_post_id_alter_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='owner_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6f96eb1b-077d-4cc1-aa87-c68b5979599c'), primary_key=True, serialize=False),
        ),
    ]
