# Generated by Django 4.2.3 on 2023-07-31 14:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_post_owner_profile_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5a150c71-0242-4d56-9875-0b3102556702'), primary_key=True, serialize=False),
        ),
    ]
