# Generated by Django 4.2.3 on 2023-07-31 14:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4cd48742-37b1-4571-8c66-3e5d50370144'), primary_key=True, serialize=False),
        ),
    ]
