# Generated by Django 4.2.3 on 2023-07-31 15:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('19db6f93-b817-40ed-9582-9233bf06398a'), primary_key=True, serialize=False),
        ),
    ]
