# Generated by Django 4.2.3 on 2023-07-31 15:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0813cca2-682c-478e-95d9-47e1399d4b57'), primary_key=True, serialize=False),
        ),
    ]
